### ISSUE TITLE
[Swagger] Request Header "User-Id"가 모든 API에 표시되는 문제

### ISSUE THREAD

**Issue by chocolaggibbiddori** [miracle-job-a/user-service#19]
> What is issue

&nbsp;&nbsp; "User-Id" 헤더 값을 Swagger 설정 파일에서 전역 파라미터로 넣어주다보니, 유저 인증 인터셉터를 거치지 않는 (ex. "/v1/user/login") API에도 해당 헤더 값이 표시되는 문제가 발생.

<br>

> Solution

&nbsp;&nbsp; 전역 파라미터에서 "User-Id"를 제거하고, 필요한 API에만 해당 파라미터를 설정해야함

<br>

> Problems

- `@Operation` 어노테이션의 parameters 속성을 통해 해당 파라미터를 명시하려 했으나 Swagger 명세에 나타나지 않음
- Swagger Editor에 들어갈 json 데이터를 직접 수정하는 방법이 있으나, 너무 귀찮음

**Comment by chocolaggibbiddori** [comment]
오 Swagger 설정에서 Docket 빈을 여러 개 지정할 수 있는 것 같은데요? 함 해보겠음

**Comment by hazzokko** [comment]
안그래도 어제 찾아봤는데 RequestHandlerProvider 를 상속하는 커스텀 핸들러를 구현한 다음 User-Id 변수를 사용하지 않는 커스텀 인터페이스 (예, @ExcludeUserIdParameter) 도 구현하면 컨트롤러에 해당 어노테이션 붙여서 해당 스웨거에서 제거하는 방법 찾았었는데 아직 적용은 못해봤어요
해결 안되면 얘기해주세요!

**Comment by hazzokko** [comment]
Good 입니다
