### ISSUE TITLE
Update 로직 수행 시 일대다 연관관계 매핑된 엔티티의 PK값이 유지되지 않는 문제

### ISSUE THREAD

**Issue by hazzokko** [miracle-job-a/user-service#20]
> What is issue

&nbsp;&nbsp; Update 로직 수행 시 자기소개서의 경우 CoverLetter 엔티티의 PK값은 유지되나, 해당 엔티티에 일대다로 연관관계 매핑된 CoverLetterQna 엔티티의 PK값은 유지되지 않고 새롭게 부여되는 문제가 발생

<br>

> Solution

&nbsp;&nbsp; 여러 시도를 해보았으나 유지되지 않아 해결방안을 고민하고 있음

<br>

> Problems

- 수정 시 기존의 qnaList 값을 clear() 하지 않으면 기존 데이터가 남아있는 상태에서 save() 메서드가 수행되어 데이터가 기존의 데이터에 추가하여 생성됨, 하지만 clear() 메서드 수행 시 기존 엔티티의 값을 삭제하고 다시 생성하므로 새로운 PK값이 부여되는 문제가 발생
- CoverLetterQna의 PK 값을 할당하려고 했으나 CoverLetter 엔티티에 해당 값을 저장하는 변수가 없어서 해당 값을 수정 시 할당할 수 없음

**Comment by chocolaggibbiddori** [comment]
어차피 clear() 하고 다시 추가할거.. 그냥 엔티티 대신 값 타입으로 사용해야 하나?

**Comment by chocolaggibbiddori** [comment]
값 타입으로 변경
