### ISSUE TITLE
자기소개서, 이력서 등록 API - Request DTO에 불필요한 필드 발견

### ISSUE THREAD

**Issue by chocolaggibbiddori** [miracle-job-a/user-service#30]
> What is issue

&nbsp;&nbsp; `CoverLetterPostRequestDto`, `ResumePostRequestDto` 클래스에 userId 필드가 존재하는데, 요청 URL에 "/user/{userId}"를 추가함으로써 해당 필드는 필요없게됨

<br>

> Solution

&nbsp;&nbsp; 해당 필드를 제거하고, Controller에서는 `@PathVariable`을 사용하는 것으로 변경이 필요함

**Comment by hazzokko** [comment]
필드 제거 후에 관련 메서드 수정해서 PR 올릴게요!

**Comment by chocolaggibbiddori** [comment]
#34 에서 해결
