### ISSUE TITLE
자기소개서 등록 API 동작 에러

### ISSUE THREAD

**Issue by chocolaggibbiddori** [miracle-job-a/user-service#31]
> What is issue

&nbsp;&nbsp; POSTMAN을 이용해서 `http://localhost:60001/v1/user/1/cover-letter` 경로로

```json
{
  "qnaList": {
    "answer": "answer1",
    "question": "question1"
  },
  "title": "한 달 만에 채용사이트를 구현할 수 있었던 비결",
  "userId": 1
}
```

다음 데이터를 보내봤는데 다음과 같은 오류 응답을 받았습니다.

```json
{
    "httpStatus": 500,
    "message": "일시적인 서버 오류입니다.",
    "code": "500",
    "exception": "HttpMessageNotReadableException"
}
```

`qnaList`가 역직렬화 되지 않는 것 같은데 확인 함 해주세용

**Comment by chocolaggibbiddori** [comment]
`qnaList` 필드가 `List` 타입이라서 배열 데이터로 넣어주어야 하네요.

```json
{
  "qnaList": [
    {
      "answer": "answer1",
      "question": "question1"
    }
  ],
  "title": "한 달 만에 채용사이트를 구현할 수 있었던 비결",
  "userId": 1
}
```

Swagger 문서 예시가 잘못된 것 같은데 `CoverLetterPostRequestDto`의 `qnaList` 필드에 있는 `@Schema` 부분을 수정해야 할 것 같습니다.

**Comment by hazzokko** [comment]
스웨거에서 제공하는 @Schema 어노테이션에서는 배열에 대한 example를 직접적으로 지원하지 않아서 계속 JSON parse error 가 떠서 example로 지정은 안될 것 같아요
구현 클래스를 지정하는 것도 배열 데이터로 들어가지 않아서 오류가 발생하는 거라 방법을 고민해봐야 할 것 같아요

**Comment by chocolaggibbiddori** [comment]
흠... 그거는 제가 한 번 찾아볼게용
