### ISSUE TITLE
이력서 careerDetailList 수정 오류

### ISSUE THREAD

**Issue by Hamel0** [miracle-job-a/user-service#47]
- [] 배열 형태로 받아오는 carrerDetailList, projectList, etcList 중에서 데이터가 [1,2,3]을 수정 요청을 보낼 시,
데이터 [1] 이 삭제 되고, [2,3] 만 저장이 됩니다.
- controller , dto 디버깅 시 모두 데이터가 넘어오고 성공은 확인 했으나, DB에 [1]번 데이터가 삭제 된 것을 확인.

**Comment by chocolaggibbiddori** [comment]
해당 엔티티들을 전부 값 타입으로 변경해서 해결할 생각입니다. 이력서 수정 요청 시 경력사항, 프로젝트, 기타사항 별로 하지 말고 이력서를 통째로 수정하면 될 것 같아요!
