### ISSUE TITLE
지원서 테이블 application_status 상태 값 수정 API 요청 건

### ISSUE THREAD

**Issue by Hamel0** [miracle-job-a/user-service#62]
> 설명
- 해당 유저의 지원현황에서 자신이 지원한 공고의 상태값을 변경을 할 수 없어서.. 수정 API 요청 드립니다.
- Api 요청에도 남김

> RequestData
- ApplicationLetterId
- Application_status

> ResponseData
- 수정 성공 여부

> 참고 사진

<img width="609" alt="image" src="https://github.com/miracle-job-a/user-service/assets/132334878/850d21de-bfbf-4787-abe9-b9bc900b2fa3">

**Comment by hazzokko** [comment]
구현 및 반영 완료했습니다!
