### ISSUE TITLE
지원 이력서 API 정보 추가 요청

### ISSUE THREAD

**Issue by kimjunyo** [miracle-job-a/user-service#66]
지원 이력서를 불러올 때 지원서 테이블의 사진 추가로 요청합니다. 
그리고 지원할 때 지원된 이력서의 사진이 지원서 테이블의 사진 컬럼에 들어가도록 요청합니다.

**Comment by kimjunyo** [comment]
이력서 목록 요청할 때도 이력서 사진 추가 요청하겠습니다.
이유: 이력서 삭제하기 시 사진 컬럼 필요.

**Comment by hazzokko** [comment]
반영 완료
